name_max_length: 50
email_max_length: 255
pass_min_length: 6
title_max_length: 150
password_reset_expired: 2

admin:
  per_page: 10
  break_time: 10

movie:
  picture_size: 5
  picture_resize_high: 260
  picture_resize_width: 185
